# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Price_Of_Low_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='\u80a1\u7968\u4ee3\u7801')),
                ('current_price', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='\u524d\u4ef7\u683c\uff08\u5f53\u65e5\u7684\u6536\u76d8\u4ef7\uff09')),
                ('current_date', models.DateField(default='', verbose_name='\u524d\u4ef7\u683c\uff08\u5f53\u65e5\u7684\u6536\u76d8\u4ef7\uff09')),
                ('high_price', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='\u6700\u9ad8\u4ef7')),
                ('high_date', models.DateField(default='', verbose_name='\u6700\u9ad8\u4ef7\u51fa\u73b0\u65e5\u671f')),
                ('low_price', models.DecimalField(decimal_places=5, default='', max_digits=10, verbose_name='\u6700\u4f4e\u4ef7')),
                ('low_date', models.DateField(default='', verbose_name='\u6700\u4f4e\u4ef7\u51fa\u73b0\u65e5\u671f')),
                ('rate', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='\u5f53\u524d\u4ef7\u4e0e\u6700\u9ad8\u4ef7\u7684\u6bd4\u503c')),
                ('ave_price_up', models.BooleanField(verbose_name='\u5747\u7ebf\u662f\u5426\u6210\u591a\u5934\u6392\u5217')),
                ('volume_up', models.BooleanField(verbose_name='\u662f\u5426\u653e\u91cf')),
                ('turnover', models.DecimalField(decimal_places=5, default='', max_digits=10, verbose_name='\u6362\u624b\u7387')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Basics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='\u80a1\u7968\u4ee3\u7801')),
                ('name', models.CharField(max_length=10, verbose_name='\u540d\u79f0')),
                ('industry', models.CharField(max_length=10, verbose_name='\u6240\u5c5e\u884c\u4e1a')),
                ('area', models.CharField(max_length=10, verbose_name='\u5730\u533a')),
                ('pe', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u5e02\u76c8\u7387')),
                ('outstanding', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u6d41\u901a\u80a1\u672c(\u4ebf)')),
                ('totals', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u603b\u80a1\u672c(\u4ebf)')),
                ('totalAssets', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u603b\u8d44\u4ea7(\u4e07)')),
                ('fixedAssets', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u56fa\u5b9a\u8d44\u4ea7')),
                ('reservedPerShare', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u6bcf\u80a1\u516c\u79ef\u91d1')),
                ('esp', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u6bcf\u80a1\u6536\u76ca')),
                ('bvps', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u6bcf\u80a1\u51c0\u8d44')),
                ('pb', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u5e02\u51c0\u7387')),
                ('timeToMarket', models.CharField(max_length=8, verbose_name='\u4e0a\u5e02\u65e5\u671f')),
                ('undp', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u672a\u5206\u5229\u6da6')),
                ('perundp', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u6bcf\u80a1\u672a\u5206\u914d')),
                ('rev', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u6536\u5165\u540c\u6bd4( %)')),
                ('profit', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u5229\u6da6\u540c\u6bd4( %)')),
                ('gpr', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u6bdb\u5229\u7387( %)')),
                ('npr', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='\u51c0\u5229\u6da6\u7387( %)')),
                ('holders', models.IntegerField(default=0, verbose_name='\u80a1\u4e1c\u4eba\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Fenshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='\u80a1\u7968\u4ee3\u7801')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('time', models.TimeField(verbose_name='\u65f6\u95f4')),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='\u4ef7\u683c')),
                ('change', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='\u4ef7\u683c\u53d8\u52a8')),
                ('volume', models.IntegerField(default=0, verbose_name='\u6210\u4ea4\u91cf')),
                ('amount', models.BigIntegerField(default=0, verbose_name='\u6210\u4ea4\u989d')),
                ('type', models.CharField(default='', max_length=6, verbose_name='\u4e70\u5356\u7c7b\u578b')),
            ],
        ),
    ]
