# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Fen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='\u80a1\u7968\u4ee3\u7801')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('time', models.TimeField(verbose_name='\u65f6\u95f4')),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='\u4ef7\u683c')),
                ('change', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='\u4ef7\u683c\u53d8\u52a8')),
                ('volume', models.IntegerField(default=0, verbose_name='\u6210\u4ea4\u91cf')),
                ('amount', models.BigIntegerField(default=0, verbose_name='\u6210\u4ea4\u989d')),
                ('type', models.CharField(default='', max_length=6, verbose_name='\u4e70\u5356\u7c7b\u578b')),
            ],
        ),
    ]
