# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20170123_1606'),
    ]

    operations = [
    ]
