#coding:utf-8
"""
Django settings for learn_models project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rpxmt3_eqp&qlhs%fngs$#u-04#g39$&*e)4)n6h3sw2ge*jj#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bootstrap_toolkit',
    'bootstrap3',
    # 注册新的app
    'learn',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'learn_models.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'learn_models.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        # sqlite 配置
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

        # mysql 配置
        'ENGINE': 'django.db.backends.mysql',  # 设置为mysql数据库
        'NAME': 'pystock',  # mysql数据库名
        'USER': 'root',  # mysql用户名，留空则默认为当前linux用户名
        'PASSWORD': 'root',  # mysql密码
        'HOST': '',  # 留空默认为localhost
        'PORT': '',  # 留空默认为3306端口
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
# BASE_DIR = os.path.dirname(os.path.dirname(__file__))
# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# 将static目录放在 STATICFILES_DIRS 中，这样就可以load到static目录下的bootstrap了
# STATIC_DIRS = (
#     os.path.join(BASE_DIR,'static'),
# )



# 变量值项目的根目录，也就是settings.py的存放位置   E:\py\learn_models\learn_models
SITE_ROOT=os.path.join(os.path.abspath(os.path.dirname(__file__)),'..')

# 然后给静态文件变量赋值，告诉Django，静态文件在哪里【静态文件变量是系统定义好的，给系统用】 E:\py\learn_models\static
STATIC_ROOT = os.path.join(SITE_ROOT,'static')

# 设置全局静态文件目录名称，可随意修改  为了生成系统默认写的url的第一个参数'^/static'   意思是给静态文件url（即STATIC_URL）一个后缀，在templates里用到的
# 【注：STATIC_URL和后面的STATICFILES_DIRS都是全局的变量，模板里可以直接用】
STATIC_URL = '/static/'

# 配置app的静态文件目录，直接在每个app目录下创建static目录，将文件直接放进去就可以了。如果Django在STATICFILES_DIRS当中没有找到的话，会到app的目录下的static目录去查找的。

# 全局的静态文件目录
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    os.path.join(os.path.dirname(__file__),'static').replace('\\','/'),
    ("css", os.path.join(STATIC_ROOT,'bootstrap/css')),
    ("js", os.path.join(STATIC_ROOT,'bootstrap/js')),
    ("fonts", os.path.join(STATIC_ROOT,'bootstrap/fonts')),
)