# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ver_front',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('flash', models.CharField(max_length=50)),
                ('bin', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=2)),
                ('dtime', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
